### ISSUE TITLE
Looking for docker version for Apple Silicon

### ISSUE THREAD

**Issue by danielnguyentb** [SolaceLabs/solace-single-docker-compose#12]
How can I get the docker image version for Apple Silicon ? The existing image only works on AMD platform, tried on Apple Silicon and got the error
```
solace_1  | Host Boot ID: a896865d-0885-4eaa-8a28-c7234009b9a6
solace_1  | Starting PubSub+ Software Event Broker Container: Wed Sep 22 17:14:57 UTC 2021
solace_1  | Setting umask to 077
solace_1  | SolOS Version: soltr_9.11.0.9
solace_1  | Failed to render config files, exiting (rc = 2)
solace_1  | runtime: failed to create new OS thread (have 2 already; errno=22)
solace_1  | fatal error: newosproc
solace_1  |
solace_1  | runtime stack:
solace_1  | runtime.throw(0xc9aa66, 0x9)
solace_1  | 	/usr/local/go/src/runtime/panic.go:596 +0x95
solace_1  | runtime.newosproc(0xc420028000, 0xc420038000)
solace_1  | 	/usr/local/go/src/runtime/os_linux.go:163 +0x18c
```

**Comment by mogongzi** [comment]
Same issue here:
`Host Boot ID: 307a883e-bc45-44e0-b804-f76fda34da06
Starting PubSub+ Software Event Broker Container: Sat Aug 6 08:00:27 UTC 2022
Setting umask to 077
SolOS Version: soltr_10.0.1.41
Failed to render config files, exiting (rc = 2)
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0xc9aa66, 0x9)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.newosproc(0xc420028000, 0xc420038000)
	/usr/local/go/src/runtime/os_linux.go:163 +0x18c
runtime.newm(0xcc6088, 0x0)
	/usr/local/go/src/runtime/proc.go:1628 +0x137
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x108d400)
	/usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc420024788 sp=0xc420024780
runtime.main()
	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200247e0 sp=0xc420024788
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200247e8 sp=0xc4200247e0`

**Comment by tomtom215** [comment]
same issue, bumping for visibility

**Comment by mogongzi** [comment]
@tomtom215 temporary solution is using `colima` as the docker engine instead of docker desktop.
